version: '3.8'

services:
  app-flask:
    build:  
      context: ./
      dockerfile: site-web.Dockerfile
    networks:
      - front-db
    ports:
      - "5010:5010"
    depends_on:
      - postgres-db
    entrypoint:
      - python3
      - /etc/app-docker.py


  postgres-db:
    image: postgres:17
    environment:
      POSTGRES_USER: "bob"
      POSTGRES_PASSWORD: "bobpass"
      POSTGRES_DB: "bobdb"
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
    networks:
      - front-db
    ports:
      - "5432:5432"

volumes:
  postgres-data:

networks:
  front-db: