version: '3.8'

services:
  postgres-db:
    image: postgres:17
    environment:
      POSTGRES_USER: "eticmont"
      POSTGRES_PASSWORD: "eticmont"
      POSTGRES_DB: "eticmont"

    volumes:
      - "postgres-data:/var/lib/postgresql/data-eticmont"

    ports:
      - "5433:5432"

volumes:
  postgres-data:
